--[[
This file is automatically generated.
DB diff for reformat.
Tables:
  NOT_EXIST_IN_SRC = 0, NOT_EXIST_IN_DST = 1, MODIFIED = 2, RENAMED = 3
Columns:
  NOT_EXIST_IN_SRC = 10, NOT_EXIST_IN_DST = 11, MODIFIED = 12, RENAMED = 13, MOVED = 14
--]]
return {
  ["Device_DHCPv4_Relay_Forwarding_ValuesTbl"] = {
      ["status"] = 1,
  },
  ["Device_DHCPv4_Relay_ValuesTbl"] = {
      ["status"] = 1,
  },
}
