--[[
This file is automatically generated.
DB diff for reformat.
Tables:
  NOT_EXIST_IN_SRC = 0, NOT_EXIST_IN_DST = 1, MODIFIED = 2, RENAMED = 3
Columns:
  NOT_EXIST_IN_SRC = 10, NOT_EXIST_IN_DST = 11, MODIFIED = 12, RENAMED = 13, MOVED = 14
--]]
return {
  ["Device_Bridging_Bridge_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["Enable"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "1",
                      ["src"] = "0",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 1",
                      ["src"] = "INTEGER DEFAULT 0",
                  },
              },
          },
          ["Status"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["check"] = {
                      ["dst"] = "(Status IN (\"Disabled\", \"Enabled\", \"Error\"))",
                      ["src"] = "(Status IN (\"Disabled\", \"Enabled\", \"Error�\"))",
                  },
                  ["default"] = {
                      ["dst"] = "\"Enabled\"",
                      ["src"] = "\"Disabled\"",
                  },
                  ["def"] = {
                      ["dst"] = "TEXT DEFAULT \"Enabled\" CHECK (Status IN (\"Disabled\", \"Enabled\", \"Error\"))",
                      ["src"] = "TEXT DEFAULT \"Disabled\" CHECK (Status IN (\"Disabled\", \"Enabled\", \"Error�\"))",
                  },
              },
          },
      },
  },
  ["Device_X_Inango_Copy_Operation_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["DstFileType"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["check"] = {
                      ["dst"] = "(DstFileType IN (\"cpu_sw\", \"gfast_dpu_fw\", \"gfast_cpe_fw\", NULL ))",
                      ["src"] = "(DstFileType IN (\"cpu_sw\", \"gfast_fw\", NULL ))",
                  },
                  ["def"] = {
                      ["dst"] = "TEXT CHECK (DstFileType IN (\"cpu_sw\", \"gfast_dpu_fw\", \"gfast_cpe_fw\", NULL ))",
                      ["src"] = "TEXT CHECK (DstFileType IN (\"cpu_sw\", \"gfast_fw\", NULL ))",
                  },
              },
          },
      },
  },
  ["Device_X_Inango_Gfast_Line_Config_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["DirectAttachMode"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "1",
                      ["src"] = "0",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 1",
                      ["src"] = "INTEGER DEFAULT 0",
                  },
              },
          },
      },
  },
  ["Device_X_Inango_Gfast_Line_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["LineId"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["def"] = {
                      ["dst"] = "INTEGER  UNIQUE",
                      ["src"] = "INTEGER",
                  },
                  ["unique"] = {
                      ["dst"] = true,
                  },
              },
          },
      },
  },
  ["Device_X_Inango_Gfast_Cfg_Profiles_TDD_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["MF"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["check"] = {
                      ["dst"] = "(MF IN (\"23\", \"36\"))",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 36 CHECK (MF IN (\"23\", \"36\"))",
                      ["src"] = "INTEGER DEFAULT 36",
                  },
              },
          },
          ["CyclicExt"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["check"] = {
                      ["dst"] = "(CyclicExt IN (\"4\", \"8\", \"10\", \"12\", \"14\", \"16\", \"20\", \"24\", \"30\", \"33\"))",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 10 CHECK (CyclicExt IN (\"4\", \"8\", \"10\", \"12\", \"14\", \"16\", \"20\", \"24\", \"30\", \"33\"))",
                      ["src"] = "INTEGER DEFAULT 10",
                  },
              },
          },
      },
  },
  ["Device_X_Inango_Gfast_Cfg_Profiles_Spectrum_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["Name"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["def"] = {
                      ["dst"] = "TEXT  UNIQUE",
                      ["src"] = "TEXT",
                  },
                  ["unique"] = {
                      ["dst"] = true,
                  },
              },
          },
      },
  },
  ["Device_X_Inango_Gfast_Cfg_Profiles_DsDR_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["MaxGDR"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "4294967295",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 4294967295",
                      ["src"] = "INTEGER",
                  },
              },
          },
          ["MinETr"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "0",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 0",
                      ["src"] = "INTEGER",
                  },
              },
          },
          ["MinGDR"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "0",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 0",
                      ["src"] = "INTEGER",
                  },
              },
          },
          ["MaxNDR"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "4294967295",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 4294967295",
                      ["src"] = "INTEGER",
                  },
              },
          },
      },
  },
  ["Device_X_Inango_Gfast_Cfg_Profiles_UsDR_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["MaxGDR"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "4294967295",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 4294967295",
                      ["src"] = "INTEGER",
                  },
              },
          },
          ["MinETr"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "0",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 0",
                      ["src"] = "INTEGER",
                  },
              },
          },
          ["MinGDR"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "0",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 0",
                      ["src"] = "INTEGER",
                  },
              },
          },
          ["MaxNDR"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "4294967295",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 4294967295",
                      ["src"] = "INTEGER",
                  },
              },
          },
      },
  },
  ["Device_IP_Interface_IPv4Address_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["X_Inango_IPAddressName"] = {
              ["status"] = 11,
          },
      },
  },
  ["Device_Bridging_Bridge_Port_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["PortState"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["check"] = {
                      ["dst"] = "(PortState IN (\"Disabled\", \"Blocking\", \"Listening\", \"Learning\", \"Forwarding\", \"Broken\"))",
                      ["src"] = "(PortState IN (\"Disabled\", \"Blocking\", \"Listening\", \"Learning\", \"Forwarding\", \"Broken.\"))",
                  },
                  ["def"] = {
                      ["dst"] = "TEXT DEFAULT \"Disabled\" CHECK (PortState IN (\"Disabled\", \"Blocking\", \"Listening\", \"Learning\", \"Forwarding\", \"Broken\"))",
                      ["src"] = "TEXT DEFAULT \"Disabled\" CHECK (PortState IN (\"Disabled\", \"Blocking\", \"Listening\", \"Learning\", \"Forwarding\", \"Broken.\"))",
                  },
              },
          },
      },
  },
  ["Device_Bridging_Bridge_VLAN_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["Enable"] = {
              ["status"] = 11,
          },
      },
  },
  ["Device_IP_Interface_IPv6Address_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["Enable"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "1",
                      ["src"] = "0",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 1",
                      ["src"] = "INTEGER DEFAULT 0",
                  },
              },
          },
      },
  },
  ["Device_DHCPv4_Client_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["Interface"] = {
              ["status"] = 11,
          },
      },
  },
  -- ***************************************************************************
  -- Manual additions
  -- ***************************************************************************
  ["Device_Users_User_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_Bridging_Bridge_VLAN_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_Bridging_Bridge_VLANPort_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_IP_Interface_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_IP_Interface_IPv4Address_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_IP_Interface_IPv6Address_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_DHCPv4_Client_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_DHCPv6_Client_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_QoS_Queue_ValuesTbl"] = {
    ["status"] = 1,
  },
}
