--[[
This file is automatically generated.
DB diff for reformat from version 01.01 to 01.02.
Tables:
  NOT_EXIST_IN_SRC = 0, NOT_EXIST_IN_DST = 1, MODIFIED = 2, RENAMED = 3
Columns:
  NOT_EXIST_IN_SRC = 10, NOT_EXIST_IN_DST = 11, MODIFIED = 12, RENAMED = 13, MOVED = 14
--]]
return {
  ["Device_X_Inango_Gfast_Line_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["Status"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["check"] = {
                      ["dst"] = "(Status IN (\"Up\", \"Down\", \"Unknown\", NULL ))",
                  },
                  ["def"] = {
                      ["dst"] = "TEXT CHECK (Status IN (\"Up\", \"Down\", \"Unknown\", NULL ))",
                      ["src"] = "TEXT",
                  },
              },
          },
      },
  },
  ["Device_X_Inango_Gfast_Cfg_Profiles_Noise_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["UsRMC_MAXBL"] = {
              ["status"] = 11,
          },
          ["UsRMC_TgtSNRM"] = {
              ["status"] = 11,
          },
          ["DsRMC_TgtSNRM"] = {
              ["status"] = 11,
          },
          ["DsRMC_MAXBL"] = {
              ["status"] = 11,
          },
      },
  },
  ["Device_X_Inango_Gfast_DFE_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["DFEStatus"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["def"] = {
                      ["dst"] = "INTEGER CHECK (DFEStatus IN (\"0\", \"1\", \"3\", NULL ))",
                      ["src"] = "TEXT CHECK (DFEStatus IN (\"0\", \"1\", \"3\", NULL ))",
                  },
                  ["type"] = {
                      ["dst"] = "INTEGER",
                      ["src"] = "TEXT",
                  },
              },
          },
          ["FWStatus"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["def"] = {
                      ["dst"] = "INTEGER CHECK (FWStatus IN (\"0\", \"1\", \"2\", \"3\", NULL ))",
                      ["src"] = "TEXT CHECK (FWStatus IN (\"0\", \"1\", \"2\", \"3\", NULL ))",
                  },
                  ["type"] = {
                      ["dst"] = "INTEGER",
                      ["src"] = "TEXT",
                  },
              },
          },
      },
  },
}
