--[[
This file is automatically generated.
DB diff for reformat.
Tables:
  NOT_EXIST_IN_SRC = 0, NOT_EXIST_IN_DST = 1, MODIFIED = 2, RENAMED = 3
Columns:
  NOT_EXIST_IN_SRC = 10, NOT_EXIST_IN_DST = 11, MODIFIED = 12, RENAMED = 13, MOVED = 14
--]]
return {
  ["Device_X_Inango_Gfast_Cfg_Profiles_Spectrum_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["Name"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["def"] = {
                      ["dst"] = "TEXT  UNIQUE",
                      ["src"] = "TEXT",
                  },
                  ["unique"] = {
                      ["dst"] = true,
                  },
              },
          },
      },
  },
  ["Device_X_Inango_NetconfServer_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["PMADiscEnable"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "0",
                      ["src"] = "1",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 0",
                      ["src"] = "INTEGER DEFAULT 1",
                  },
              },
          },
      },
  },
  ["Device_X_Inango_Proprietary_VLAN_ValuesTbl"] = {
      ["status"] = 1,
  },
  ["Device_IP_Interface_IPv4Address_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["X_Inango_IPAddressName"] = {
              ["status"] = 11,
          },
      },
  },
  ["Device_X_Inango_Gfast_Line_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["LineId"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["def"] = {
                      ["dst"] = "INTEGER  UNIQUE",
                      ["src"] = "INTEGER",
                  },
                  ["unique"] = {
                      ["dst"] = true,
                  },
              },
          },
      },
  },
  ["Device_Bridging_Bridge_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["Enable"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "1",
                      ["src"] = "0",
                  },
                  ["def"] = {
                      ["dst"] = "INTEGER DEFAULT 1",
                      ["src"] = "INTEGER DEFAULT 0",
                  },
              },
          },
          ["Status"] = {
              ["status"] = 12,
              ["diff"] = {
                  ["default"] = {
                      ["dst"] = "\"Enabled\"",
                      ["src"] = "\"Disabled\"",
                  },
                  ["def"] = {
                      ["dst"] = "TEXT DEFAULT \"Enabled\" CHECK (Status IN (\"Disabled\", \"Enabled\", \"Error\"))",
                      ["src"] = "TEXT DEFAULT \"Disabled\" CHECK (Status IN (\"Disabled\", \"Enabled\", \"Error\"))",
                  },
              },
          },
      },
  },
  ["Device_DHCPv4_Client_ValuesTbl"] = {
      ["status"] = 2,
      ["diff"] = {
          ["Interface"] = {
              ["status"] = 11,
          },
      },
  },
  -- ***************************************************************************
  -- Manual additions
  -- ***************************************************************************
  ["Device_Users_User_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_Bridging_Bridge_VLAN_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_Bridging_Bridge_VLANPort_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_IP_Interface_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_IP_Interface_IPv4Address_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_IP_Interface_IPv6Address_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_DHCPv4_Client_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_DHCPv6_Client_ValuesTbl"] = {
    ["status"] = 1,
  },
  ["Device_QoS_Queue_ValuesTbl"] = {
    ["status"] = 1,
  },
}
