#!/bin/sh
################################################################################
#
# inango-prplmesh_product_info_upd
# 
# Copyright (c) 2013-2021 Inango Systems LTD.
#
# Author: Inango Systems LTD. <support@inango-systems.com>
# Creation Date: 2020/09/23
#
# The author may be reached at support@inango-systems.com
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 
# Subject to the terms and conditions of this license, each copyright holder
# and contributor hereby grants to those receiving rights under this license
# a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable
# (except for failure to satisfy the conditions of this license) patent license
# to make, have made, use, offer to sell, sell, import, and otherwise transfer
# this software, where such license applies only to those patent claims, already
# acquired or hereafter acquired, licensable by such copyright holder or contributor
# that are necessarily infringed by:
# 
# (a) their Contribution(s) (the licensed copyrights of copyright holders and
# non-copyrightable additions of contributors, in source or binary form) alone;
# or
# 
# (b) combination of their Contribution(s) with the work of authorship to which
# such Contribution(s) was added by such copyright holder or contributor, if,
# at the time the Contribution is added, such addition causes such combination
# to be necessarily infringed. The patent license shall not apply to any other
# combinations which include the Contribution.
# 
# Except as expressly stated above, no rights or licenses from any copyright
# holder or contributor is granted under this license, whether expressly, by
# implication, estoppel or otherwise.
# 
# DISCLAIMER
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# NOTE
# 
# This is part of a management middleware software package called MMX that was developed by Inango Systems Ltd.
# 
# This version of MMX provides web and command-line management interfaces.
# 
# Please contact us at Inango at support@inango-systems.com if you would like to hear more about
# - other management packages, such as SNMP, TR-069 or Netconf
# - how we can extend the data model to support all parts of your system
# - professional sub-contract and customization services
# 
################################################################################

if [ -z "$MMX_DEFAULTS_PRODUCT_FILE" ] ; then
    MMX_DEFAULTS_PATH="/usr/lib/mmx/mmx-defaults"
    MMX_DEFAULTS_PRODUCT_FILE="${MMX_DEFAULTS_PATH}/product_info"
fi

if [ -z "$upgr_log_file" ] ; then
    upgr_log_file="/etc/customer_config_upgrade.log"
fi

echo "Board product info processing"   >> $upgr_log_file
rt_prod_file="/etc/mmx/product_info"
cp ${MMX_DEFAULTS_PRODUCT_FILE}  $rt_prod_file
echo "cp ${MMX_DEFAULTS_PRODUCT_FILE}  $rt_prod_file" >> $upgr_log_file

# Read board product info from the flash memory and save it in the product file
# Reading flash memory is platform depended opearation;
# Currently winpath platform utility is used.
# TODO: add flash read support for other CPU platforms)

if [ -e /bin/flash-env-util -a -x /bin/flash-env-util ] ; then
    flash_cmd="flash-env-util env "
fi

if [ -n "$flash_cmd" ] ; then
    SN=`$flash_cmd BOARD_SN 2>/dev/null | cut -f 2 -d"="`
    MNFC=`$flash_cmd BOARD_MANUFACTURER 2>/dev/null | cut -f 2 -d"="`
    MNFC_OUI=`$flash_cmd BOARD_MFC_OUI 2>/dev/null | cut -f 2 -d"="`
    MNFC_PEN=`$flash_cmd BOARD_MFC_PEN 2>/dev/null | cut -f 2 -d"="`
    PRODCLASS=`$flash_cmd BOARD_PROD_CLASS 2>/dev/null | cut -f 2 -d"="`
    MODEL=`$flash_cmd BOARD_MODEL 2>/dev/null | cut -f 2 -d"="`
    DESCR=`$flash_cmd BOARD_DESCRIPTION 2>/dev/null | cut -f 2 -d"="`
    HWREV=`$flash_cmd BOARD_HW_REV 2>/dev/null | cut -f 2 -d"="`
    BOARDMAC=`$flash_cmd BOARD_MAC_DFE0 2>/dev/null | cut -f 2 -d"="`
    BOARDMACETHX=`$flash_cmd BOARD_MAC_ETHX 2>/dev/null | cut -f 2 -d"="`
fi

echo "Serial number read from flash is: $SN" >> $upgr_log_file
echo "Mnfctr: $MNFC, Mfc OUI: $MNFC_OUI, Mfc PEN: $MNFC_PEN"  >> $upgr_log_file
echo "Prod class: $PRODCLASS, Model: $MODEL" >> $upgr_log_file
echo "Board description: $DESCR, Board MAC: $BOARDMAC" >> $upgr_log_file
   
[ -n "$SN" ] && sed -i 's/^SerialNumber=.*/SerialNumber='"$SN"'/g' $rt_prod_file
[ -n "$MNFC" ] && sed -i 's/^Manufacturer=.*/Manufacturer='"$MNFC"'/g' $rt_prod_file
[ -n "$MNFC_OUI" ] && sed -i 's/^ManufacturerOUI=.*/ManufacturerOUI='"$MNFC_OUI"'/g' $rt_prod_file
[ -n "$MNFC_PEN" ] && sed -i 's/^EnterpriseNumber=.*/EnterpriseNumber='"$MNFC_PEN"'/g' $rt_prod_file
[ -n "$PRODCLASS" ] && sed -i 's/^ProductClass=.*/ProductClass='"$PRODCLASS"'/g' $rt_prod_file
[ -n "$MODEL" ] && sed -i 's/^ModelName=.*/ModelName='"$MODEL"'/g' $rt_prod_file
[ -n "$DESCR" ] && sed -i 's/^Description=.*/Description='"$DESCR"'/g' $rt_prod_file
[ -n "$HWREV" ] && sed -i 's/^HardwareVersion=.*/HardwareVersion='"$HWREV"'/g' $rt_prod_file
[ -n "$BOARDMAC" ] && sed -i 's/^BoardMACAddress=.*/BoardMACAddress='"$BOARDMAC"'/g' $rt_prod_file
[ -n "$BOARDMACETHX" ] && sed -i 's/^BoardBaseMACAddress=.*/BoardBaseMACAddress='"$BOARDMACETHX"'/g' $rt_prod_file


echo "Runtime product file: $rt_prod_file" >> $upgr_log_file
echo "------------------------------------------------------" >> $upgr_log_file

